apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "langsmith.fullname" . }}-{{ .Values.playground.name }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
    {{- with.Values.playground.deployment.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
    {{- with.Values.playground.deployment.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.playground.autoscaling.enabled }}
  replicas: {{ .Values.playground.deployment.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "langsmith.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "langsmith.fullname" . }}-{{ .Values.playground.name }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      {{- with .Values.playground.deployment.annotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- with.Values.playground.deployment.labels }}
            {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "langsmith.labels" . | nindent 8 }}
        app.kubernetes.io/component: {{ include "langsmith.fullname" . }}-{{ .Values.playground.name }}
    spec:
      securityContext:
        {{- toYaml .Values.playground.deployment.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "playground.serviceAccountName" . }}
      containers:
        - name: {{ .Values.playground.name }}
          {{- with.Values.playground.deployment.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.playground.deployment.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.global.azure.images.playgroundImage.registry }}/{{ .Values.global.azure.images.playgroundImage.image }}:{{ .Values.global.azure.images.playgroundImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.global.azure.images.playgroundImage.pullPolicy }}
          ports:
            - name: playground
              containerPort: {{ .Values.playground.containerPort }}
              protocol: TCP
          startupProbe:
            httpGet:
              path: /ok
              port: {{ .Values.playground.containerPort }}
            failureThreshold: 6
            periodSeconds: 10
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /ok
              port: {{ .Values.playground.containerPort }}
            failureThreshold: 6
            periodSeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /ok
              port: {{ .Values.playground.containerPort }}
            failureThreshold: 6
            periodSeconds: 10
            timeoutSeconds: 1
          resources:
            {{- toYaml .Values.playground.deployment.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.playground.deployment.securityContext | nindent 12 }}
          {{- with .Values.playground.deployment.volumeMounts }}
          volumeMounts:
              {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.playground.deployment.extraContainerConfig }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- with .Values.playground.deployment.sidecars }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.playground.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.playground.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.playground.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.playground.deployment.volumes }}
      volumes:
          {{- toYaml . | nindent 8 }}
      {{- end }}
