{{- if not .Values.postgres.external.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "langsmith.fullname" . }}-{{ .Values.postgres.name }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
    {{- with.Values.postgres.statefulSet.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
    {{- with.Values.postgres.statefulSet.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  serviceName: {{ include "langsmith.fullname" . }}-{{ .Values.postgres.name }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "langsmith.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "langsmith.fullname" . }}-{{ .Values.postgres.name }}
  template:
    metadata:
      {{- with .Values.postgres.statefulSet.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- with.Values.postgres.statefulSet.labels }}
            {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "langsmith.labels" . | nindent 8 }}
        app.kubernetes.io/component: {{ include "langsmith.fullname" . }}-{{ .Values.postgres.name }}
    spec:
      securityContext:
        {{- toYaml .Values.postgres.statefulSet.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "postgres.serviceAccountName" . }}
      containers:
        - name: {{ .Values.postgres.name }}
          {{- with.Values.postgres.statefulSet.command }}
          command:
             {{ . }}
          {{- end }}
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "langsmith.postgresSecretsName" .}}
                  key: postgres_db
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "langsmith.postgresSecretsName" .}}
                  key: postgres_password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "langsmith.postgresSecretsName" .}}
                  key: postgres_user
            - name: PGDATA
              value: /var/lib/postgresql/data/postgres
            {{- with .Values.postgres.statefulSet.extraEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          image: "{{ .Values.global.azure.images.postgresImage.registry }}/{{ .Values.global.azure.images.postgresImage.image }}:{{ .Values.global.azure.images.postgresImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.global.azure.images.postgresImage.pullPolicy }}
          ports:
            - name: postgres
              containerPort: {{ .Values.postgres.containerPort }}
              protocol: TCP
          startupProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -d {{ .Values.postgres.external.database }} -U {{ .Values.postgres.external.user }}
            failureThreshold: 6
            periodSeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -d {{ .Values.postgres.external.database }} -U {{ .Values.postgres.external.user }}
            failureThreshold: 6
            periodSeconds: 10
            timeoutSeconds: 1
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -d {{ .Values.postgres.external.database }} -U {{ .Values.postgres.external.user }}
            failureThreshold: 6
            periodSeconds: 10
            timeoutSeconds: 1
          resources:
            {{- toYaml .Values.postgres.statefulSet.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.postgres.statefulSet.securityContext | nindent 12 }}
          volumeMounts:
            {{- with .Values.postgres.statefulSet.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            - mountPath: /var/lib/postgresql/data
              name: data
              subPath: postgres
          {{- with .Values.postgres.statefulSet.extraContainerConfig }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- with .Values.postgres.statefulSet.sidecars }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.postgres.statefulSet.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.postgres.statefulSet.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.postgres.statefulSet.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.postgres.statefulSet.volumes }}
      volumes:
          {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
        labels:
          {{- include "langsmith.selectorLabels" . | nindent 10 }}
          app.kubernetes.io/component: {{ include "langsmith.fullname" . }}-{{ .Values.postgres.name }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.postgres.statefulSet.persistence.size }}
        {{- if .Values.postgres.statefulSet.persistence.storageClassName }}
        storageClassName: {{ .Values.postgres.statefulSet.persistence.storageClassName }}
        {{- end }}
 {{- end}}
