apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "langsmith.fullname" . }}-{{ .Values.queue.name }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
    {{- with.Values.queue.deployment.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
    {{- with.Values.queue.deployment.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.queue.autoscaling.enabled }}
  replicas: {{ .Values.queue.deployment.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "langsmith.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "langsmith.fullname" . }}-{{ .Values.queue.name }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      {{- with .Values.queue.deployment.annotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- with.Values.queue.deployment.labels }}
            {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "langsmith.labels" . | nindent 8 }}
        app.kubernetes.io/component: {{ include "langsmith.fullname" . }}-{{ .Values.queue.name }}
    spec:
      securityContext:
        {{- toYaml .Values.queue.deployment.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "queue.serviceAccountName" . }}
      restartPolicy: Always
      containers:
        - name: {{ .Values.queue.name }}
          {{- with.Values.queue.deployment.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: "REDIS_MAX_CONNECTIONS"
              value: "250"
            - name: "ASYNCPG_POOL_MAX_SIZE"
              value: "3"
            {{- include "langsmith.commonEnv" . | nindent 12 }}
            {{- with .Values.queue.deployment.extraEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "langsmith.fullname" . }}-config
          image: "{{ .Values.global.azure.images.backendImage.registry }}/{{ .Values.global.azure.images.backendImage.image }}:{{ .Values.global.azure.images.backendImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.global.azure.images.backendImage.pullPolicy }}
          resources:
            {{- toYaml .Values.queue.deployment.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.queue.deployment.securityContext | nindent 12 }}
          {{- with .Values.queue.deployment.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.queue.deployment.extraContainerConfig }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- with .Values.queue.deployment.sidecars }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.queue.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.queue.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.queue.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.queue.deployment.volumes }}
      volumes:
          {{- toYaml . | nindent 8 }}
      {{- end }}
